# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d8e33b1a6d2edc08c97f3bca153294cc46e5c43fd2fae998baf184cee05a3c09862ef982e02d555c248ed5072ed2caddd1b8903d386356a03ffcb168d13fa04

test:
  secret_key_base: 185f63c159bb9cdddb8f05897af3d5005886e2d59c901df02099a5d8cfcc0115b274b8b691e628b4b20ff2cc544e820cc237522848465e5ffd7c44beb8d3e79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
